language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t cb3-user-api . --build-arg JWT_SECRET=$JWT_SECRET --build-arg AWS_BUCKET=$AWS_BUCKET --build-arg AWS_PROFILE=$AWS_PROFILE --build-arg AWS_REGION=$AWS_REGION --build-arg POSTGRES_DB=$POSTGRES_DB --build-arg POSTGRES_HOST=$POSTGRES_HOST --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD --build-arg POSTGRES_USERNAME=$POSTGRES_USERNAME --build-arg URL=$URL
  - docker tag cb3-user-api curtbryan3rd/cb3-user-api:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push curtbryan3rd/cb3-user-api